config/routes.rb
TeamE::Application.routes.draw do
  

  get "dashboard/index"
  get "dashboard/:user_id" => "dashboard#show", as: 'user_dashboard'
  get "send_email/:user_id" => "dashboard#send_email", as: "user_email"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  post "events/create"

  root 'dashboard#index'

  

end

app/models/eat_event.rb
class EatEvent < Event

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  scope :default_period, -> { where('event_date > ?', 21.days.ago) }
end

app/models/exercise_event.rb
class ExerciseEvent < Event

end

app/models/outdoor_event.rb
class OutdoorEvent < Event

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :eat_events, dependent: :destroy
  has_many :exercise_events, dependent: :destroy
  has_many :outdoor_events, dependent: :destroy

  def eaten_today?
    eat_events.exists?(event_date: Date.today)
  end

  def exercised_today?
    exercise_events.exists?(event_date: Date.today)
  end

  def outside_today?
    outdoor_events.exists?(event_date: Date.today)
  end

  def finished_exercise?
    exercise_events.where("event_date >= ?", (Date.today - 21.days)).count >= 21
  end

  def finished_eat?
    eat_events.where("event_date >= ?", (Date.today - 21.days)).count >= 21
  end

  def finished_outdoors?
    outdoor_events.where("event_date >= ?", (Date.today - 21.days)).count >= 21
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:user_id])
    @eat_events = @user.eat_events.default_period
    @outdoor_events = @user.outdoor_events.default_period
    @exercise_events = @user.exercise_events.default_period
    
   
    @suggestion = Suggestion.find(@user.id % 3 + 3)  # want suggestions 3, 4 and 5
    @suggestion_what = @suggestion.what
    @suggestion_why = @suggestion.why
    @suggestion_where = @suggestion.where
  
  end

  def send_email
    @user = User.find(params[:user_id])
    UserMailer.morning_status_email(@user).deliver
    redirect_to user_dashboard_path(@user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  protect_from_forgery with: :null_session
  def create
    @event = event_type.new(event_params)
    if @event.save
      user = User.find(params[:event][:user_id])
      event = "#{@event.class.to_s.underscore.gsub("_event","")}_record"
      user.increment(event)
      user.save
      redirect_to user_dashboard_path(user.id)
    else
      redirect_to :root
    end
  end

  private
  def event_type
    params[:event].delete(:type).constantize
  end

  def event_params
    params.require(:event).permit(:event_date, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_eat_icon.html.erb
<svg version="1.1" id="eat-icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   width="303.988px" height="303.992px" viewBox="0 0 303.988 303.992" enable-background="new 0 0 303.988 303.992"
   xml:space="preserve">
<g id="Eat">
  <g>
    <g>
      <path d="M49.655,282.852c-7.926,7.926-20.761,7.973-28.619,0.114l0,0c-7.871-7.871-7.824-20.707,0.101-28.632l143.618-143.619
        c7.927-7.927,20.76-7.972,28.632-0.101l0,0c7.858,7.858,7.813,20.693-0.113,28.62L49.655,282.852z"/>
      <g>
        <path d="M286.766,68.165l-55.151,55.152c-2.818,2.818-7.387,2.828-10.202,0.011c-2.827-2.826-2.806-7.381,0.013-10.2
          l56.169-56.169l-10.195-10.196l-56.175,56.174c-2.815,2.817-7.374,2.84-10.204,0.01c-2.802-2.802-2.801-7.383,0.015-10.2
          l56.175-56.174L247.036,26.4l-56.175,56.174c-2.815,2.816-7.385,2.829-10.208,0.006c-2.786-2.787-2.803-7.385,0.013-10.202
          l55.158-55.157c-8.156-3.743-17.939-2.386-24.462,4.137l-61.281,61.281c-8.459,8.46-8.248,22.392,0.512,31.152l39.592,39.592
          c8.751,8.752,22.705,8.983,31.165,0.523l61.275-61.276C289.17,86.13,290.504,76.314,286.766,68.165z"/>
      </g>
    </g>
  </g>
</g>
</svg>

app/views/dashboard/_exercise_icon.html.erb
<svg id="exercise-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="303.988px" height="303.992px" viewBox="0 0 303.988 303.992" enable-background="new 0 0 303.988 303.992"
	 xml:space="preserve">
<g id="Explore">
</g>
<g id="Eat">
</g>
<g id="Exercise">
	<g>
		<g>
			<path d="M94.57,268.578c-27.027,0-52.751-29.446-55.973-33.29l21.468-18.119c9.66,11.378,28.3,26.08,36.837,22.928
				c1.662-0.618,16.22-7.914,15.669-72.462v-0.239c0.03-2.729,0.985-67.533,33.705-118.652l23.659,15.149
				c-27.877,43.562-29.217,100.983-29.266,103.656c0.491,58.703-10.325,90.129-34.022,98.9
				C102.643,267.931,98.593,268.578,94.57,268.578z"/>
		</g>
		<g>
			<path d="M236.184,276.587l-27.877-3.533c6.928-54.621,1.217-90.609-16.084-101.377c-17.621-10.964-48.449,4.322-57.855,10.536
				l-15.495-23.446c2.103-1.389,51.733-33.637,88.187-10.951C235.41,165.464,244.934,207.571,236.184,276.587z"/>
		</g>
		<g>
			<path d="M196.98,127.678c-5.035,0-9.939-0.704-14.695-2.124c-33.964-10.149-44.501-52.565-44.928-54.358l27.325-6.552
				l-13.664,3.279l13.655-3.319c1.959,7.941,10.4,29.525,25.725,34.04c13.363,3.946,32.092-4.9,54.109-25.608l19.248,20.466
				C239.586,116.237,217.193,127.678,196.98,127.678z"/>
		</g>
		<g>
			<path d="M60.496,176.249c-0.125-1.832-0.347-3.888-0.586-6.126c-2.683-24.762-8.956-82.729,84.396-109.233l7.682,27.025
				c-70.543,20.03-66.691,55.624-64.145,79.188c0.279,2.538,0.54,4.949,0.697,7.229L60.496,176.249z"/>
		</g>
		<g>
			<path d="M277.924,77.04c0,9.763-7.914,17.678-17.676,17.678c-9.764,0-17.674-7.915-17.674-17.678
				c0-9.773,7.91-17.675,17.674-17.675C270.01,59.365,277.924,67.27,277.924,77.04z"/>
		</g>
		<g>
			<path d="M91.335,185.502c-2.681,9.4-12.474,14.821-21.863,12.13c-9.381-2.694-14.821-12.464-12.127-21.864
				c2.691-9.379,12.474-14.811,21.864-12.119C88.595,166.332,94.027,176.125,91.335,185.502z"/>
		</g>
		<g>
			<path d="M238.729,280.688c0,9.753-7.914,17.674-17.676,17.674c-9.764,0-17.678-7.923-17.678-17.674
				c0-9.773,7.914-17.68,17.678-17.68C230.818,263.009,238.729,270.915,238.729,280.688z"/>
		</g>
		<g>
			<circle cx="43.739" cy="219.408" r="17.675"/>
		</g>
		<g>
			<path d="M192.291,37.79c0,17.773-14.406,32.178-32.178,32.178c-17.753,0-32.16-14.405-32.16-32.178
				c0-17.762,14.403-32.16,32.16-32.16C177.885,5.633,192.291,20.027,192.291,37.79z"/>
		</g>
	</g>
</g>
</svg>

app/views/dashboard/_habit_bar.html.erb
<svg class="habit-bar" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   width="605.058px" height="50px" viewBox="0 0 605.058 50" enable-background="new 0 0 605.058 50"
   xml:space="preserve">
<g>
<% xspan = 29.107 %>
<% event_count = 0 %>
<% if (Date.today - events.first.event_date) < 21 %>
  <% ((events.first.event_date..events.last.event_date)).each_with_index do |date, index| %>
    <% if events.any? { |event| event.event_date == date } %>
      <rect fill="#82C560" x="<%= xspan * index %>" width="22.921" height="50"/>
    <% else %>
      <rect fill="#D2E2C9" x="<%= xspan * index %>" width="22.921" height="50"/>
    <% end %>
    <% event_count += 1 %>
  <% end %>
  <% (event_count..21).each do |index| %>
    <rect fill="#D2E2C9" x="<%= xspan * index %>" width="22.921" height="50"/>
  <% end %>
<% else %>
  <% ((Date.today - 20.days)..Date.today).each_with_index do |date, index| %>
    <% if events.any? { |event| event.event_date == date } %>
      <rect fill="#82C560" x="<%= xspan * index %>" width="22.921" height="50"/>
    <% else %>
      <rect fill="#D2E2C9" x="<%= xspan * index %>" width="22.921" height="50"/>
    <% end %>
  <% end %>
<% end %>
</g>
</svg>

app/views/dashboard/_outdoor_icon.html.erb
<svg version="1.1" id="outdoor-icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="303.988px" height="303.992px" viewBox="0 0 303.988 303.992" enable-background="new 0 0 303.988 303.992"
	 xml:space="preserve">
<g id="Explore">
	<g>
		<path d="M252.72,139.209c-3.488-11.825-14.781-19.112-26.18-17.514c-1.096,0.157-2.199,0.388-3.295,0.708l-13.936,4.117
			c-0.471,0.025-0.932,0.007-1.395-0.041c-4.086-0.412-7.842-3.536-9.203-8.127c-1.734-5.852,1.129-11.871,6.404-13.427l2.797-0.83
			v-0.411l19.49-5.754c12.449-3.682,19.441-17.163,15.611-30.124c-3.82-12.966-17.012-20.476-29.479-16.806l-28.422,8.406
			c-0.346,0.024-0.707,0.055-1.064,0.055c-6.525,0-11.83-5.293-11.83-11.822c0-0.739,0.068-1.472,0.201-2.174l-0.201-0.158V29.987
			c0-11.107-8.988-20.094-20.092-20.094c-0.046,0-0.095,0-0.137,0c-0.046,0-0.094,0-0.139,0c-11.102,0-20.092,8.987-20.092,20.094
			v15.322l-0.212,0.158c0.14,0.708,0.212,1.435,0.212,2.174c0,6.529-5.305,11.822-11.837,11.822c-0.351,0-0.711-0.031-1.061-0.055
			L90.44,51.002c-12.458-3.676-25.648,3.84-29.476,16.806c-3.84,12.96,3.165,26.442,15.61,30.124l19.498,5.754v0.411l2.798,0.83
			c5.275,1.556,8.14,7.575,6.407,13.427c-1.356,4.591-5.12,7.715-9.208,8.127c-0.457,0.048-0.92,0.066-1.387,0.041l-13.938-4.117
			c-1.1-0.321-2.199-0.552-3.298-0.708c-11.413-1.599-22.686,5.7-26.177,17.514c-3.831,12.956,3.158,26.431,15.61,30.113
			l29.191,8.623v0.145l13.43,3.963c5.266,1.541,8.352,6.813,6.897,11.734c-1.39,4.721-6.452,7.42-11.518,6.27l-6.634-1.963
			c-0.452-0.141-0.894-0.246-1.344-0.355l-0.831-0.25v0.049c-11.67-2.6-22.699,1.764-25.221,10.309
			c-2.68,9.061,5.248,19.377,17.702,23.063l63.424,18.717v0.025l0.018-0.012l0.018,0.012v-0.025l63.434-18.717
			c12.455-3.686,20.359-14.002,17.695-23.063c-2.521-8.545-13.555-12.908-25.225-10.309v-0.049l-0.84,0.25
			c-0.447,0.109-0.887,0.215-1.344,0.355l-6.637,1.963c-5.066,1.15-10.135-1.549-11.521-6.27c-1.455-4.922,1.631-10.193,6.9-11.734
			l13.426-3.963v-0.145l29.191-8.623C249.56,165.648,256.551,152.166,252.72,139.209z"/>
		<path d="M146.477,286.662c0,2.02,2.474,3.674,5.517,3.674s5.517-1.646,5.517-3.674V70.515c0-2.035-2.474-3.682-5.517-3.682
			s-5.517,1.641-5.517,3.682V286.662z"/>
	</g>
</g>
</svg>

app/views/dashboard/_suggestion_today.html.erb
<div class="row do-today">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Today's Tip: <%= @suggestion_what %></h2>
      </div>
      <div class="panel-body row">
        <div class="col-xs-6">
          <h4>Where in Vermont?</h4>
          <%= @suggestion_where %>
        </div>
        <div class="col-xs-6">
          <h4>For your health:</h4>
          <p>
          <%= @suggestion_why %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_the_button.html.erb
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="303.988px" height="303.992px" viewBox="0 0 303.988 303.992" enable-background="new 0 0 303.988 303.992"
	 xml:space="preserve">
 <g id="Explore" class="<%= 'done' if @user.outside_today? %> button-segment explore" onclick="formSubmit('outdoor_form')">
	<path id="explore" fill="#3992A9" d="M20.35,227.982c26.261,45.44,75.333,76.01,131.645,76.01
		c56.312,0,105.384-30.568,131.647-76.01l-131.647-75.987L20.35,227.982z"/>
	<g>
		<path fill="#71C16A" d="M184.48,228.523c-1.125-3.813-4.766-6.164-8.443-5.648c-0.354,0.051-0.709,0.125-1.063,0.229l-4.494,1.328
			c-0.152,0.008-0.301,0.002-0.449-0.014c-1.318-0.133-2.529-1.141-2.969-2.621c-0.559-1.887,0.365-3.828,2.066-4.33l0.902-0.268
			v-0.133l6.285-1.855c4.016-1.188,6.271-5.535,5.035-9.715c-1.232-4.182-5.486-6.604-9.506-5.42l-9.166,2.711
			c-0.113,0.008-0.229,0.018-0.344,0.018c-2.105,0-3.816-1.707-3.816-3.813c0-0.238,0.023-0.474,0.066-0.701l-0.066-0.051v-4.941
			c0-3.582-2.898-6.481-6.479-6.481c-0.015,0-0.03,0-0.044,0c-0.015,0-0.03,0-0.045,0c-3.58,0-6.48,2.899-6.48,6.481v4.941
			l-0.068,0.051c0.045,0.229,0.068,0.463,0.068,0.701c0,2.106-1.71,3.813-3.817,3.813c-0.113,0-0.229-0.01-0.342-0.018l-9.167-2.711
			c-4.017-1.186-8.271,1.238-9.506,5.42c-1.238,4.18,1.021,8.527,5.035,9.715l6.288,1.855v0.133l0.902,0.268
			c1.701,0.502,2.625,2.443,2.066,4.33c-0.437,1.48-1.651,2.488-2.969,2.621c-0.148,0.016-0.297,0.021-0.448,0.014l-4.495-1.328
			c-0.354-0.104-0.709-0.178-1.063-0.229c-3.681-0.516-7.317,1.838-8.443,5.648c-1.235,4.178,1.019,8.524,5.035,9.711l9.414,2.781
			v0.047l4.331,1.278c1.698,0.498,2.693,2.197,2.224,3.785c-0.448,1.521-2.081,2.392-3.714,2.021l-2.14-0.633
			c-0.146-0.045-0.288-0.08-0.434-0.115l-0.267-0.08v0.016c-3.764-0.838-7.321,0.568-8.134,3.324
			c-0.864,2.922,1.692,6.25,5.709,7.438l20.454,6.037v0.008l0.006-0.004l0.006,0.004v-0.008l20.457-6.037
			c4.016-1.188,6.566-4.516,5.707-7.438c-0.814-2.756-4.371-4.162-8.135-3.324v-0.016l-0.27,0.08
			c-0.145,0.035-0.287,0.07-0.434,0.115l-2.141,0.633c-1.633,0.371-3.268-0.5-3.715-2.021c-0.469-1.588,0.525-3.287,2.225-3.785
			l4.33-1.278v-0.047l9.414-2.781C183.461,237.05,185.715,232.701,184.48,228.523z"/>
		<path fill="#3D763E" d="M151.027,275.826c0,0.652,0.531,1.186,1.186,1.186c0.654,0,1.186-0.531,1.186-1.186v-69.707
			c0-0.656-0.531-1.188-1.186-1.188c-0.655,0-1.186,0.53-1.186,1.188V275.826z"/>
	</g>
</g>
<g id="Eat" class="<%= 'done' if @user.eaten_today? %> button-segment eat" onclick="formSubmit('eat_form')">
	<path id="eat" fill="#4DC5E5" d="M151.995,0v151.995l131.647,75.987c12.92-22.354,20.346-48.287,20.346-75.987
		C303.988,67.982,236.008,0,151.995,0z"/>
	<g>
		<g>
			<circle fill="#ECECEC" cx="218.77" cy="104.173" r="31.369"/>
			<circle fill="#CFCECE" cx="218.771" cy="104.173" r="23.526"/>
		</g>
		<g>
			<path fill="#ECECEC" d="M264.133,127.498c0,1.728-1.123,3.132-2.504,3.132l0,0c-1.383,0-2.506-1.404-2.506-3.132V96.19
				c0-1.728,1.123-3.132,2.506-3.132l0,0c1.381,0,2.504,1.404,2.504,3.132V127.498z"/>
			<g>
				<path fill="#ECECEC" d="M266.102,78.253v12.023c0,0.614-0.4,1.113-0.895,1.113c-0.496,0-0.895-0.499-0.895-1.113V78.031h-1.791
					v12.246c0,0.614-0.398,1.113-0.895,1.113c-0.492,0-0.895-0.499-0.895-1.113V78.031h-1.787v12.246c0,0.614-0.4,1.113-0.896,1.113
					c-0.49,0-0.895-0.499-0.895-1.113V78.253c-1.045,0.481-1.785,1.695-1.785,3.117v13.359c0,1.844,1.242,3.34,2.781,3.34h6.955
					c1.537,0,2.783-1.496,2.783-3.34V81.371C267.891,79.949,267.146,78.734,266.102,78.253z"/>
			</g>
		</g>
		<g>
			<g>
				<ellipse fill="#ECECEC" cx="175.34" cy="88.05" rx="7.516" ry="10.019"/>
				<path fill="#ECECEC" d="M177.846,127.498c0,1.728-1.121,3.132-2.506,3.132l0,0c-1.383,0-2.506-1.404-2.506-3.132V96.19
					c0-1.728,1.123-3.132,2.506-3.132l0,0c1.385,0,2.506,1.404,2.506,3.132V127.498z"/>
			</g>
			<ellipse fill="#CFCECE" cx="175.34" cy="87.617" rx="5.229" ry="6.97"/>
		</g>
	</g>
</g>
<g id="Exercise" class="<%= 'done' if @user.exercised_today? %> button-segment exercise" onclick="formSubmit('exercise_form')">
	<path id="exercise" fill="#267184" d="M151.995,0C67.982,0,0,67.982,0,151.996c0,27.7,7.428,53.635,20.35,75.987l131.645-75.987V0z
		"/>
	<g>
		<g>
			<path fill="#ECECEC" d="M62.262,143.807c-8.315,0-16.23-9.06-17.221-10.242l6.605-5.575c2.972,3.5,8.707,8.024,11.334,7.054
				c0.511-0.19,4.99-2.435,4.821-22.294v-0.074c0.009-0.84,0.303-20.778,10.37-36.506l7.279,4.661
				c-8.577,13.403-8.989,31.07-9.004,31.892c0.151,18.061-3.177,27.73-10.468,30.429C64.746,143.608,63.5,143.807,62.262,143.807z"
				/>
		</g>
		<g>
			<path fill="#ECECEC" d="M105.833,146.271l-8.577-1.087c2.131-16.805,0.374-27.878-4.949-31.191
				c-5.421-3.373-14.906,1.33-17.8,3.242l-4.768-7.214c0.647-0.427,15.917-10.349,27.133-3.369
				C105.595,112.082,108.525,125.037,105.833,146.271z"/>
		</g>
		<g>
			<path fill="#ECECEC" d="M93.771,100.456c-1.549,0-3.058-0.217-4.521-0.653C78.8,96.68,75.558,83.63,75.427,83.078l8.407-2.016
				l-4.204,1.009l4.201-1.021c0.603,2.443,3.2,9.084,7.915,10.473c4.112,1.214,9.874-1.508,16.648-7.879l5.922,6.297
				C106.88,96.936,99.99,100.456,93.771,100.456z"/>
		</g>
		<g>
			<path fill="#ECECEC" d="M51.779,115.4c-0.039-0.564-0.107-1.196-0.181-1.885c-0.825-7.618-2.755-25.453,25.967-33.608
				l2.363,8.315c-21.704,6.163-20.519,17.114-19.735,24.364c0.086,0.781,0.166,1.523,0.214,2.224L51.779,115.4z"/>
		</g>
		<g>
			<path fill="#F37353" d="M118.675,84.876c0,3.004-2.435,5.439-5.438,5.439c-3.004,0-5.438-2.435-5.438-5.439
				c0-3.007,2.434-5.438,5.438-5.438C116.24,79.438,118.675,81.87,118.675,84.876z"/>
		</g>
		<g>
			<path fill="#F37353" d="M61.267,118.247c-0.825,2.892-3.838,4.56-6.727,3.732c-2.886-0.829-4.56-3.835-3.731-6.727
				c0.828-2.886,3.838-4.557,6.727-3.729C60.424,112.349,62.095,115.362,61.267,118.247z"/>
		</g>
		<g>
			<path fill="#F37353" d="M106.616,147.533c0,3.001-2.435,5.438-5.438,5.438c-3.004,0-5.439-2.438-5.439-5.438
				c0-3.007,2.435-5.439,5.439-5.439C104.182,142.094,106.616,144.526,106.616,147.533z"/>
		</g>
		<g>
			<circle fill="#F37353" cx="46.623" cy="128.679" r="5.438"/>
		</g>
		<g>
			<path fill="#F37353" d="M92.328,72.8c0,5.468-4.432,9.9-9.9,9.9c-5.462,0-9.895-4.432-9.895-9.9c0-5.465,4.432-9.895,9.895-9.895
				C87.896,62.906,92.328,67.335,92.328,72.8z"/>
		</g>
	</g>
</g>
</svg>
<form action="<%= events_create_path(event: {event_date: Date.today, user_id: @user.id, type: "EatEvent"}) %>"
  method="POST"
  id="eat_form">
</form>
<form action="<%= events_create_path(event: {event_date: Date.today, user_id: @user.id, type: "ExerciseEvent"}) %>"
  method="POST"
  id="exercise_form">
</form>
<form action="<%= events_create_path(event: {event_date: Date.today, user_id: @user.id, type: "OutdoorEvent"}) %>"
  method="POST"
  id="outdoor_form">
</form>

app/views/dashboard/index.html.erb
<div class="home-content">
  <div class="row about">
    <div class="col-md-12">
      <h1>Healthy Habit VT</h1>
      <h2>"Your path to healthy habits"</h2>
    </div>
  </div>
  .
</div>

app/views/dashboard/show.html.erb
<div id="send_email"><%= link_to " ", user_email_path(@user) %></div>
    <div class="container main-content">
    	<div class="row">
  			<div class="col-md-5 button-wrap">
          <h3>What did you do today?</h3>
          <%= render "the_button" %>
  			</div>
  			<div class="col-md-7">
          <div class="row">
            <h3 class="pull-left">Path to Habit</h3>
            <h3 class="pull-right">Record</h3>
          </div>
  				<div class="row streak-status">
            <div class="<%= 'finished' if @user.finished_exercise? %> col-xs-1 col-md-1"><%= render partial: 'exercise_icon' %></div>
            <div class="col-xs-10 col-md-10">
              <%= render partial: "habit_bar", locals: {events: @exercise_events} %>
            </div>
            <div class="col-xs-1 col-md-1 streak-number"><p><%= @user.exercise_record %></p></div>
  				</div>
  				
  				<div class="row streak-status">
            <div class="<%= 'finished' if @user.finished_eat? %> col-xs-1 col-md-1"><%= render partial: 'eat_icon' %></div>
            <div class="col-xs-10 col-md-10">
              <%= render partial: "habit_bar", locals: {events: @eat_events} %>
            </div>
            <div class="col-xs-1 col-md-1 streak-number"><p><%= @user.eat_record %></p></div>
  				</div>
  				
  				<div class="row streak-status">
            <div class="<%= 'finished' if @user.finished_outdoors? %> col-xs-1 col-md-1"><%= render partial: 'outdoor_icon' %></div>
            <div class="col-xs-10 col-md-10">
              <%= render partial: "habit_bar", locals: {events: @outdoor_events} %>
            </div>
            <div class="col-xs-1 col-md-1 streak-number"><p><%= @user.outdoor_record %></p></div>
  				</div>
  			</div>
		</div>
		
    <%= render partial: 'suggestion_today' %>
    </div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">

    <title>Team E App</title>

    <!-- Bootstrap core CSS -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>


    <!-- Custom styles for this template -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
  </head>

  <body>
    <%= render partial: 'shared/nav' %> 
    
    <%= yield %>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

app/views/shared/_nav.html.erb
<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">Healthy Habit VT</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a data-toggle="dropdown" href="#"><%= @user.nil? ? "Users" : @user.name %></a>
              <ul class="dropdown-menu pull-right">
                <% User.all.each do |user| %>
                  <li><%= link_to user.name, user_dashboard_path(user) %></li>
                <% end %>
              </ul>
            </li>
          </ul>
          </div>
        </div><!--/.nav-collapse -->
      </div>
    </div>